---
output: html_document
editor_options: 
  chunk_output_type: console
---
#title: "Calcular parámetros hidrográficos con r.watershed. Visualizar con leaflet"

```{r, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  collapse=TRUE,
  eval = T
)
options(knitr.duplicate.label = "allow")
```


## ejecutar Scrit anteriores

```{r, include=FALSE}
source(
  knitr::purl(
    'proyeccion-importar-fuente-extension_C_Propia.Rmd',
    output=tempfile()
  )
)
knitr::opts_chunk$set(fig.path = "img/calcwshed/")
```

## `g.list`

```{r}
execGRASS(
  'g.list',
  flags = 't',
  parameters = list(
    type = c('raster', 'vector')
  )
)
```

## Calcular parámetros hidrográficos de interés usando `r.watershed`

```{r}
execGRASS(
  "r.watershed",
  flags = c('overwrite','quiet'),
  parameters = list(
    elevation = "dem",
    accumulation = "accum-de-rwshed",
    stream = "stream-de-rwshed",
    drainage = "drainage-dir-de-rwshed",
    basin = 'basins',
    half_basin = 'half-basins',
    threshold = 80
  )
)
```


## Traer capas a R

```{r, results='hide'}
# Usar Spatial 
library(sp)
use_sp()
#Paquete manejo de los raster
library(raster)
#DEM
dem <- raster(readRAST('dem'))
#Basins
basins <- raster(readRAST('basins'))
#Stream network
stream <- raster(readRAST('stream-de-rwshed'))
stream3857 <- projectRaster(stream, crs = CRS("+init=epsg:3857"), method = 'ngb')
#Generar un vectorial de extensión de capa en EPSG:4326
e <- extent(stream)
e <- as(e, 'SpatialPolygons')
proj4string(e) <- CRS("+init=epsg:32619")
e <- spTransform(e, CRSobj = CRS("+init=epsg:4326"))
```


## Visualizar capas con `leaflet`

```{r}
library(leaflet)
library(leafem)
r_wshed_salida <- leaflet() %>%
  addProviderTiles(providers$Stamen.Terrain, group = 'terrain') %>%
  addRasterImage(dem, group='DEM', opacity = 0.5) %>%
  addRasterImage(
    ratify(basins),
    group='basins', opacity = 0.7,
    colors = sample(rep(RColorBrewer::brewer.pal(12, 'Set3'),1000))) %>% 
  addRasterImage(stream3857, project = F, group='str', opacity = 0.7, method = 'ngb', colors = 'blue') %>% 
  addLayersControl(
    overlayGroups = c('terrain','DEM','basins','str'),
    options = layersControlOptions(collapsed=FALSE)) %>% 
  addHomeButton(extent(e), 'Ver todo')
r_wshed_salida
#La siguiente línea toma una captura de este mapa (toma tiempo, paciencia)
r_wshed_salida %>% mapview::mapshot(file = 'r_wshed_salida.png')
```

## Limpiar archivo de bloqueo del conjunto de mapas de GRASS. Quitar máscara, si la hubiere

```{r}
source('borrar_mascara_si_la_hubiere.R')
unlink_.gislock()
```