---
output: html_document
editor_options: 
  chunk_output_type: inline
---
### Curva e integral hipsométrica

```{r, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE,
  collapse=TRUE,
  eval = T
)
options(knitr.duplicate.label = "allow")
```

```{r, include=FALSE}
source(
  knitr::purl(
    'orden-de-red.Rmd',
    output=tempfile()
  )
)
knitr::opts_chunk$set(fig.path = "img/hypsocurve/")
```

## Imprimir lista de mapas ráster y vectoriales dentro en la región/localización activa


```{r}
execGRASS(
  'g.list',
  flags = 't',
  parameters = list(
    type = c('raster', 'vector')
  )
)
```

## Representar cuencas

```{r, results='hide', warning=FALSE, message=FALSE}
library(sp)
use_sp()
library(mapview)
bas2 <- readVECT('r_stream_basins_2')
bas3 <- readVECT('r_stream_basins_3')
```

## Curva e integral hipsométrica

```{r, results='hide', warning=FALSE, message=FALSE}
source('integral_hypsometric_curve.R') #Cargada como función "HypsoIntCurve"
HypsoBasinsOrder2 <- HypsoIntCurve(
  basins = 'r_stream_basins_2',
  dem = 'dem',
  labelfield = 'cat',
  nrow = 2,
  labelsize = 4
)
```

```{r}
HypsoBasinsOrder2$HypsoInt
HypsoBasinsOrder2$HypsoCurve
mapview(bas2, zcol='cat', col.regions = 'blue', legend = FALSE) %>%
  addStaticLabels(label = bas2$cat)
```

```{r, results='hide', warning=FALSE, message=FALSE}
HypsoBasinsOrder3 <- HypsoIntCurve(
  basins = 'r_stream_basins_3',
  dem = 'dem',
  labelfield = 'cat',
  nrow = 1,
  labelsize = 4
)
```

```{r}
HypsoBasinsOrder3$HypsoInt
HypsoBasinsOrder3$HypsoCurve
mapview(bas3, zcol='cat', col.regions = 'blue', legend = FALSE) %>%
  addStaticLabels(label = bas3$cat)
```

## Limpiar archivo de bloqueo del conjunto de mapas de GRASS

```{r}
unlink_.gislock()
```
